#!/bin/bash

PUBLIC_GPG_KEY=93B0E5FD
CURRENT=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DOTFILES=$( cd "$CURRENT/.." && pwd )

#-------------------------------------------------------------------------------
# Symlink all the dotfiles
ignored_files=(init LICENSE-MIT.txt mackup.cfg README.md .editorconfig)
ignored() {
    local e
    for e in "${ignored_files[@]}"; do
        [[ "$e" == "$1" ]] && return 0
    done
    return 1
}
for path in $DOTFILES/*; do
    file=$(basename $path)
    if ! ignored $file; then
        ln -sf $path $HOME/.$file
    fi
done;

# Symlink the .editorconfig explicitly
ln -sf $DOTFILES/.editorconfig $HOME/.editorconfig

# Ensure we have the local git config file
touch $HOME/.gitconfig.local

#-------------------------------------------------------------------------------
# Run the script for the respective platform
case "$(uname -s)" in
    Darwin) $CURRENT/bootstrap-osx.sh ;;
    Linux) $CURRENT/bootstrap-linux.sh ;;
    CYGWIN*|MINGW*|MSYS*) $CURRENT/bootstrap-win.sh ;;
    *) echo "Running on unknown OS. Aborting!" ; exit 1 ;;
esac

#-------------------------------------------------------------------------------
# Install the Node dependencies for the CLI scripts
if command -v npm >/dev/null 2>&1; then
    ( cd "$DOTFILES/bin" && npm install )
fi
