#!/bin/bash

CURRENT=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DOTFILES=$( cd "$CURRENT/.." && pwd )

#-------------------------------------------------------------------------------
# Symlink all the dotfiles
ignored_files=(init LICENSE-MIT.txt mackup.cfg README.md .editorconfig gnupg)
ignored() {
    local e
    for e in "${ignored_files[@]}"; do
        [[ "$e" == "$1" ]] && return 0
    done
    return 1
}
for path in $DOTFILES/*; do
    file=$(basename $path)
    if ! ignored $file; then
        ln -sf $path $HOME/.$file
    fi
done;

# Symlink the .editorconfig explicitly
ln -sf $DOTFILES/.editorconfig $HOME/.editorconfig

#-------------------------------------------------------------------------------
# Create GPG directory and symlink its files explicitly
if [ ! -d $HOME/.gnupg ]; then
    echo "Creating GPG directory; will ask for password..."
    mkdir $HOME/.gnupg && sudo chmod 700 $HOME/.gnupg
fi
ln -sf $DOTFILES/gnupg/gpg.conf $HOME/.gnupg/gpg.conf
ln -sf $DOTFILES/gnupg/gpg-agent.conf $HOME/.gnupg/gpg-agent.conf

#-------------------------------------------------------------------------------
# Ensure we have the local git config file
touch $HOME/.gitconfig.local

#-------------------------------------------------------------------------------
# Create a Projects folder
[ ! -d "$HOME/Projects/arduino" ] && mkdir -p $HOME/Projects/arduino
[ ! -d "$HOME/Projects/golang/src" ] && mkdir -p $HOME/Projects/golang/src


#-------------------------------------------------------------------------------
# Install hey
if [ ! -d $HOME/.hey ]; then
    git clone https://github.com/hedlund/hey.git $HOME/.hey
fi

#-------------------------------------------------------------------------------
# Run the script for the respective platform
case "$(uname -s)" in
    Darwin) $CURRENT/bootstrap-osx.sh ;;
    Linux) $CURRENT/bootstrap-linux.sh ;;
    CYGWIN*|MINGW*|MSYS*) $CURRENT/bootstrap-win.sh ;;
    *) echo "Running on unknown OS. Aborting!" ; exit 1 ;;
esac
