#!/bin/bash

# Get the script directory
CURRENT=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

###############################################################################
# Mac OS X                                                                    #
###############################################################################
if [[ "$(uname -s)" == "Darwin" ]]; then

    # Make sure these login items are removed...
    osascript -e 'tell application "System Events" to delete login item "Spotify"'
    osascript -e 'tell application "System Events" to delete login item "Google Chrome"'
    osascript -e 'tell application "System Events" to delete login item "Steam"'

    # Register some software licenses
    [ -f $HOME/Dropbox/Library/Licenses/register.sh ] && $HOME/Dropbox/Library/Licenses/register.sh

fi


##############################################################################
# Install the last stuff                                                     #
##############################################################################

$CURRENT/install-npm.sh
$CURRENT/install-code.sh
$CURRENT/install-go.sh
