#!/usr/bin/env bash

# Get the script directory
CURRENT=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

case "$(uname -s)" in
    ##########################################################################
    # Mac OS X                                                               #
    ##########################################################################
    Darwin)
        $CURRENT/install-brew.sh
        $CURRENT/install-cask.sh
        ;;

    ##########################################################################
    # Linux                                                                  #
    ##########################################################################
    Linux)
        if [ -n "$(which apt-get)" ]; then
            $CURRENT/install-apt.sh
            $CURRENT/install-umake.sh
        else
            echo "Installation is only compatible with Ubuntu-based distros. Aborting!"
            exit 1
        fi
        ;;

    ##########################################################################
    # Windows                                                                #
    ##########################################################################
    CYGWIN*|MINGW32*|MSYS*)
        $CURRENT/install-choco.sh
        ;;

    ##########################################################################
    # Unknown / error                                                        #
    ##########################################################################
    *)
        echo "Running on unknown OS. Aborting!"
        exit 1
        ;;
esac


##############################################################################
# Common stuff                                                               #
##############################################################################

$CURRENT/install-npm.sh
$CURRENT/install-code.sh
