#!/usr/bin/env bash

# Get the script directory
CURRENT=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

case "$(uname -s)" in
    ##########################################################################
    # Mac OS X                                                               #
    ##########################################################################
    Darwin)
        $CURRENT/install-brew.sh
        $CURRENT/install-cask.sh
        $CURRENT/install-fonts.sh

        # Start Dropbox to get the synch going as soon as possible
        open -a dropbox

        # Open up the Little Snitch installer
        LITTLESNITCH_PATH="/opt/homebrew-cask/Caskroom/little-snitch"
        if [[ "$(brew cask info little-snitch)" =~ $LITTLESNITCH_PATH/([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            VERSION="${BASH_REMATCH[1]}"
            open "$LITTLESNITCH_PATH/$VERSION/Little Snitch Installer.app"
        fi
        ;;

    ##########################################################################
    # Linux                                                                  #
    ##########################################################################
    Linux)
        if [ -n "$(which apt-get)" ]; then
            $CURRENT/install-apt.sh
        else
            echo "Installation is only compatible with Ubuntu-based distros. Aborting!"
            exit 1
        fi
        ;;

    ##########################################################################
    # Windows                                                                #
    ##########################################################################
    CYGWIN*|MINGW32*|MSYS*)
        $CURRENT/install-choco.sh
        ;;

    ##########################################################################
    # Unknown / error                                                        #
    ##########################################################################
    *)
        echo "Running on unknown OS. Aborting!"
        exit 1
        ;;
esac


##############################################################################
# Common stuff                                                               #
##############################################################################

$CURRENT/install-sdk.sh
$CURRENT/install-npm.sh
$CURRENT/install-apm.sh
$CURRENT/install-pip.sh
