#!/usr/bin/env bash

###############################################################################
# Mac OS X                                                                    #
###############################################################################
if [[ "$(uname -s)" == "Darwin" ]]; then

    # Install software
    brew cask install intellij-idea-ce
    brew cask install adobe-creative-cloud
    brew cask install steam
    brew cask install unity
fi

###############################################################################
# Mac OS X & Linux                                                            #
###############################################################################
if [[ "$(uname -s)" =~ Darwin*|Linux* ]]; then

    # rcup the personal settings
    rcup -t personal

fi

###############################################################################
# Generate SSH key                                                            #
###############################################################################

printf "\nGenerating a new SSH key..."
ssh-keygen -t rsa -b 4096 -C "henrik@hedlund.im"
