#!/usr/bin/env bash

###############################################################################
# Mac OS X                                                                    #
###############################################################################
if [[ "$(uname -s)" == "Darwin" ]]; then

    # Install software
    brew cask install adobe-creative-cloud
    brew cask install steam
fi

###############################################################################
# Generate SSH key                                                            #
###############################################################################

printf "\nGenerating a new SSH key..."
ssh-keygen -t rsa -b 4096 -C "henrik@hedlund.im"

###############################################################################
# Configure Git                                                               #
###############################################################################

git config --file ~/.gitconfig.local user.name "Henrik Hedlund"
git config --file ~/.gitconfig.local user.email "henrik@hedlund.im"
