#!/usr/bin/env bash

###############################################################################
# Mac OS X                                                                    #
###############################################################################
if [[ "$(uname -s)" == "Darwin" ]]; then

    # Install software
    brew cask install adobe-creative-cloud
    brew cask install steam
fi

###############################################################################
# Configure Git                                                               #
###############################################################################

git config --file ~/.gitconfig.local user.name "Henrik Hedlund"
git config --file ~/.gitconfig.local user.email "henrik@hedlund.im"
