#!/bin/bash

CURRENT=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#-------------------------------------------------------------------------------
# Run the script for the respective platform
case "$(uname -s)" in
    Darwin) $CURRENT/setup-osx.sh ;;
    Linux) $CURRENT/setup-linux.sh ;;
    CYGWIN*|MINGW*|MSYS*) $CURRENT/setup-win.sh ;;
    *) echo "Running on unknown OS. Aborting!" ; exit 1 ;;
esac
