#!/bin/bash

###############################################################################
# Mac OS X                                                                    #
###############################################################################
if [[ "$(uname -s)" == "Darwin" ]]; then

    # Install software
    brew install maven
    brew cask install skype
    brew cask install skype-for-business
    brew cask install java

fi

###############################################################################
# Configure Git                                                               #
###############################################################################

git config --file ~/.gitconfig.local user.name "Henrik Hedlund"
git config --file ~/.gitconfig.local user.email "henrik.hedlund@knowit.no"
