#!/usr/bin/env bash

###############################################################################
# Configure Git                                                               #
###############################################################################

git config --file ~/.gitconfig.local user.name "Henrik Hedlund"
git config --file ~/.gitconfig.local user.email "henrik.hedlund@knowit.no"
