#!/usr/bin/env bash

###############################################################################
# Generate SSH key                                                            #
###############################################################################

printf "\nGenerating a new SSH key..."
ssh-keygen -t rsa -b 4096 -C "henrik.hedlund@knowit.no"

###############################################################################
# Configure Git                                                               #
###############################################################################

git config --global user.name "Henrik Hedlund"
git config --global user.email "henrik.hedlund@knowit.no"
