#!/bin/bash

function task_configure_gnome() {
  # Enable dark mode
  gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

  # Configure theme
  gsettings set org.gnome.desktop.background color-shading-type 'solid'
  gsettings set org.gnome.desktop.background picture-options 'zoom'
  gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/gnome/blobs-l.svg'
  gsettings set org.gnome.desktop.background picture-uri-dark 'file:///usr/share/backgrounds/gnome/blobs-d.svg'
  gsettings set org.gnome.desktop.background primary-color '#86b6ef'
  gsettings set org.gnome.desktop.background secondary-color '#000000'
  gsettings set org.gnome.desktop.screensaver color-shading-type 'solid'
  gsettings set org.gnome.desktop.screensaver picture-options 'zoom'
  gsettings set org.gnome.desktop.screensaver picture-uri 'file:///usr/share/backgrounds/gnome/blobs-l.svg'
  gsettings set org.gnome.desktop.screensaver primary-color '#86b6ef'
  gsettings set org.gnome.desktop.screensaver secondary-color '#000000'
  
  # Automatic timezone
  gsettings set org.gnome.desktop.datetime automatic-timezone true
  gsettings set org.gnome.desktop.interface clock-format '24h'

  # Configure touchpad
  gsettings set org.gnome.desktop.peripherals.touchpad two-finger-scrolling-enabled true
  gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true

  # Configure interface
  gsettings set org.gnome.desktop.a11y always-show-universal-access-status true
  gsettings set org.gnome.desktop.interface show-battery-percentage true

  # Configure Ptyxis Terminal
  default_profile=$(gsettings get org.gnome.Ptyxis default-profile-uuid)
  gsettings set org.gnome.Ptyxis font-name 'FiraCode Nerd Font Mono 12'
  gsettings set org.gnome.Ptyxis use-system-font false

  # Configure Files
  dconf write "/org/gtk/gtk4/settings/file-chooser/sort-directories-first" "true"
  dconf write "/org/gtk/settings/file-chooser/clock-format" "'24h'"
}