#!/bin/bash
set -euo pipefail

echo "Remember the password you specify, you need to enter it after reboot..."
sudo mokutil --import /usr/share/surface-secureboot/surface.cer
echo "Reboot now to finalize importing certificate. Then re-enable Secure Boot..."
