#!/bin/bash

function task-enable-surface-secureboot() {
  echo "Remember the password you specify, you need to enter it after reboot..."
  sudo mokutil --import /usr/share/surface-secureboot/surface.cer
  echo "Reboot now to finalize importing certificate. Then re-enable Secure Boot..."
}
