#!/bin/bash
set -euo pipefail

flatpak install --user --noninteractive flathub page.kramo.Cartridges
flatpak install --user --noninteractive flathub org.godotengine.Godot
flatpak install --user --noninteractive flathub com.heroicgameslauncher.hgl
flatpak install --user --noninteractive flathub io.itch.itch
flatpak install --user --noninteractive flathub com.valvesoftware.Steam
