#!/bin/bash

function task-install-syncthing() {
  # Create relevant folders
  mkdir -p "${HOME}/.config/syncthing"
  mkdir -p "${HOME}/.config/containers/systemd"
  mkdir -p "${HOME}/.var/app/org.gnome.Shotwell/data"
  
  # Link config file
  ln -sf "${HOME}/.dotfiles/config/syncthing.container" "${HOME}/.config/containers/systemd/syncthing.container"

  # Start service if needed
  if [ "$(systemctl --user is-enabled syncthing.service)" = "not-found" ]; then
    echo "Starting syncthing service..."
    systemctl --user daemon-reload
    systemctl --user start syncthing.service
  fi
}
